use_frameworks!

platform :ios, '9.0'

target 'LJTableViewKit_Example' do
  pod 'LJTableViewKit', :path => '../'

  target 'LJTableViewKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
